### ISSUE TITLE
ModuleNotFoundError: No module named 'modules'

### ISSUE THREAD

**Issue by achaosss** [git-cloner/avatarify-webrtc#1]
(venv) C:\Users\Z19070948\Desktop\webrtc_test\avatarify-webrtc>python main.py
Traceback (most recent call last):
  File "C:\Users\Z19070948\Desktop\webrtc_test\avatarify-webrtc\main.py", line 17, in <module>
    from afy.cam_fomm import fomm_load_predictor, fomm_change_face, fomm_change_frame, fomm_test_predictor, InitOutPipe, InitLiveKitCli
  File "C:\Users\Z19070948\Desktop\webrtc_test\avatarify-webrtc\afy\cam_fomm.py", line 17, in <module>
    from afy import predictor_local
  File "C:\Users\Z19070948\Desktop\webrtc_test\avatarify-webrtc\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'

**Comment by little51** [comment]
Confirm whether the clone fcomm，It is in the project root.
git clone https://github.com/alievk/first-order-model.git fomm.
such as:
avatarify-webrtc
- afy
- fomm
- model

**Comment by achaosss** [comment]
> 
It works. Thanks.
